Update Lambda example
awsdocs/aws-rust-developer-guide-v1 pull request #19
Opened 2022-10-07 04:02 UTC by calavera

This PR updates the Lambda example with a more up to date implementation. It also changes the building section to use Cargo Lambda because it's currently the recommended approach, simplifying that step for customers.

Fixes https://github.com/awslabs/aws-lambda-rust-runtime/issues/537

2022-10-07 04:03 UTC, calavera reviewed
This change aligns with the current documentation in the Lambda Runtime's README and examples: https://github.com/awslabs/aws-lambda-rust-runtime

2022-10-07 22:46 UTC, DavidSouther requested changes
Thank you, calavera, for taking the time to update this! Looks really solid overall, just a couple nits around using captured identifiers.

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +    let client_ref = &s3_client;
Just take the reference at the call site, no need to separate it out.

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +                "Successfully stored the incoming request in S3 with the name '{}'",
`'{filename}'`

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +                    "the lambda has successfully stored the your request in S3 with name '{}'",
Same, '{filename}'

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +                &filename,
'{filename}', '{err}'

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +    let filename = format!("{}.txt", chrono::offset::Utc::now().timestamp());
I don't think it's worth pulling in the entire chrono crate for generating a file name. Was std::time not giving the right values for the name?

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +        write!(f, "{}", err_as_json)
mcv is enough for string interpolation, `"{err_as_json}"`

2022-10-07 22:46 UTC, DavidSouther commented on doc_source/lambda.md
> +    tracing_subscriber::fmt()
I almost want a default tracing_subscriber with these settings for Lambda... I'll copy this to the docs examples, thanks!

(No action needed)

2023-01-18 17:30 UTC, DavidSouther approved these changes

2023-01-19 20:42 UTC, merged